[book]
authors = ["Vyacheslav Fedorov"]
language = "ru"
multilingual = false
src = "src"
title = "Разработка и применение программного обеспечения в физических исследованиях"

[output.html]
mathjax-support = true
url = "https://phys-dev.github.io/book/"
git-repository-url = "https://github.com/phys-dev/book/"
